# Generated by Django 4.2 on 2026-05-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
