# Generated by Django 4.2 on 2026-05-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registration_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_permissions',
        ),
    ]
