# Generated by Django 4.2 on 2026-05-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_registration_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('one_person_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_days_stay', models.IntegerField()),
                ('image', models.ImageField(upload_to='places/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_rating', models.FloatField()),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_image', models.ImageField(upload_to='hotels/')),
                ('hotel_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='app.place')),
            ],
        ),
    ]
