# Generated by Django 4.2 on 2026-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_bookingmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/'),
        ),
    ]
