# Generated by Django 4.2 on 2026-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_booking_identity_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.CharField(default=12000, max_length=200),
            preserve_default=False,
        ),
    ]
